### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by budgierless** [Jan-E/php7-ffmpeg#1]
/php-7.0.0/include/php/main/php_config.h:2188:0: note: this is the location of the previous definition
In file included from /opt/php-7.0.0/include/php/main/php.h:400:0,
                 from /usr/local/src/php5-build/php-7.0.0/ffmpeg-php/ffmpeg-php.c:40:
/php-7.0.0/include/php/Zend/zend_virtual_cwd.h:218:2: error: unknown type name 'time_t'
/php-7.0.0/include/php/Zend/zend_virtual_cwd.h:248:86: error: unknown type name 'time_t'
/usr/local/src/php5-build/php-7.0.0/ffmpeg-php/ffmpeg-php.c: In function 'zm_startup_ffmpeg':
/usr/local/src/php5-build/php-7.0.0/ffmpeg-php/ffmpeg-php.c:108:5: warning: implicit declaration of function 'avcodec_init' [-Wimplicit-function-declaration]
make: **\* [ffmpeg-php.lo] Error 1

**Comment by yuxianhua** [comment]
1、mv /usr/local/include/libavutil/time.h /usr/local/include/libavutil/time.h_
2、make
3、mv /usr/local/include/libavutil/time.h_ /usr/local/include/libavutil/time.h

**Comment by Jan-E** [comment]
BTW: This extension needs FFmpeg 0.7.16, a really old FFmpeg version.
