### ISSUE TITLE
Errors in php7

### ISSUE THREAD

**Issue by joosung** [Jan-E/php7-ffmpeg#10]
Please can you let me know that How To Install FFmpeg and FFmpeg-PHP Extension on CentOS 7 with php7.2

When I install it on php7.2, I get the following error:
error: too many arguments to function 'zend_hash_find'
error: expected expression before 'ff_movie_context'

**Comment by Jan-E** [comment]
Could you try the Windows Fix branch? Remove the headers that are still there and try it with your own FFmpeg version.
https://github.com/Jan-E/php7-ffmpeg/tree/windows_fix

**Comment by Jan-E** [comment]
Or try the main branch
