### ISSUE TITLE
Error on make php 7.3 Please Fix

### ISSUE THREAD

**Issue by natiq2004** [Jan-E/php7-ffmpeg#11]
make
/bin/sh php7-ffmpeg-master/libtool --mode=compile cc  -I. -Iphp7-ffmpeg-master -DPHP_ATOM_INC -Iphp7-ffmpeg-master/include -Iphp7-ffmpeg-master/main -Iphp7-ffmpeg-master -I/opt/cpanel/ea-php73/root/usr/include/php -I/opt/cpanel/ea-php73/root/usr/include/php/main -I/opt/cpanel/ea-php73/root/usr/include/php/TSRM -I/opt/cpanel/ea-php73/root/usr/include/php/Zend -I/opt/cpanel/ea-php73/root/usr/include/php/ext -I/opt/cpanel/ea-php73/root/usr/include/php/ext/date/lib -I/usr/local/include/libavcodec/ -I/usr/local/include/libavformat/ -I/usr/local/include/libavutil/ -I/usr/local/include/libswscale/ -I/usr/local/include/libavfilter/ -I/usr/local/include/libavdevice/  -DHAVE_CONFIG_H  -g -O2 -Wall -fno-strict-aliasing   -c php7-ffmpeg-master/ffmpeg-php.c -o ffmpeg-php.lo
libtool: compile:  cc -I. -Iphp7-ffmpeg-master -DPHP_ATOM_INC -Iphp7-ffmpeg-master/include -Iphp7-ffmpeg-master/main -Iphp7-ffmpeg-master -I/opt/cpanel/ea-php73/root/usr/include/php -I/opt/cpanel/ea-php73/root/usr/include/php/main -I/opt/cpanel/ea-php73/root/usr/include/php/TSRM -I/opt/cpanel/ea-php73/root/usr/include/php/Zend -I/opt/cpanel/ea-php73/root/usr/include/php/ext -I/opt/cpanel/ea-php73/root/usr/include/php/ext/date/lib -I/usr/local/include/libavcodec/ -I/usr/local/include/libavformat/ -I/usr/local/include/libavutil/ -I/usr/local/include/libswscale/ -I/usr/local/include/libavfilter/ -I/usr/local/include/libavdevice/ -DHAVE_CONFIG_H -g -O2 -Wall -fno-strict-aliasing -c php7-ffmpeg-master/ffmpeg-php.c  -fPIC -DPIC -o .libs/ffmpeg-php.o
In file included from /usr/include/sys/stat.h:106:0,
                 from /opt/cpanel/ea-php73/root/usr/include/php/Zend/zend_stream.h:26,
                 from /opt/cpanel/ea-php73/root/usr/include/php/Zend/zend.h:37,
                 from /opt/cpanel/ea-php73/root/usr/include/php/main/php.h:33,
                 from php7-ffmpeg-master/ffmpeg-php.c:40:
/usr/include/bits/stat.h:91:21: error: field 'st_atim' has incomplete type
     struct timespec st_atim;  /* Time of last access.  */
                     ^
/usr/include/bits/stat.h:92:21: error: field 'st_mtim' has incomplete type
     struct timespec st_mtim;  /* Time of last modification.  */
                     ^
/usr/include/bits/stat.h:93:21: error: field 'st_ctim' has incomplete type
     struct timespec st_ctim;  /* Time of last status change.  */
                     ^
/usr/include/bits/stat.h:152:21: error: field 'st_atim' has incomplete type
     struct timespec st_atim;  /* Time of last access.  */
                     ^
/usr/include/bits/stat.h:153:21: error: field 'st_mtim' has incomplete type
     struct timespec st_mtim;  /* Time of last modification.  */
                     ^
/usr/include/bits/stat.h:154:21: error: field 'st_ctim' has incomplete type
     struct timespec st_ctim;  /* Time of last status change.  */
                     ^
In file included from /opt/cpanel/ea-php73/root/usr/include/php/Zend/zend_stream.h:26:0,
                 from /opt/cpanel/ea-php73/root/usr/include/php/Zend/zend.h:37,
                 from /opt/cpanel/ea-php73/root/usr/include/php/main/php.h:33,
                 from php7-ffmpeg-master/ffmpeg-php.c:40:
/usr/include/sys/stat.h:366:31: error: array type has incomplete element type
         const struct timespec __times[2],
                               ^
/usr/include/sys/stat.h:373:54: error: array type has incomplete element type
 extern int futimens (int __fd, const struct timespec __times[2]) __THROW;
                                                      ^
In file included from /opt/cpanel/ea-php73/root/usr/include/php/main/php.h:466:0,
                 from php7-ffmpeg-master/ffmpeg-php.c:40:
/opt/cpanel/ea-php73/root/usr/include/php/Zend/zend_virtual_cwd.h:189:2: error: unknown type name 'time_t'
  time_t                         expires;
  ^
/opt/cpanel/ea-php73/root/usr/include/php/Zend/zend_virtual_cwd.h:219:89: error: unknown type name 'time_t'
 CWD_API realpath_cache_bucket* realpath_cache_lookup(const char *path, size_t path_len, time_t t);
                                                                                         ^
make: *** [ffmpeg-php.lo] Error 1

**Comment by natiq2004** [comment]
Jan-E commits this patch
https://github.com/Jan-E/php7-ffmpeg/pull/9/commits

===Installing ffmpeg-php 7.3 For Cpanel EasyApache 4===
cd /root

wget --no-check-certificate https://codeload.github.com/Jan-E/php7-ffmpeg/zip/master -O /root/php7-ffmpeg-master.zip

unzip php7-ffmpeg-master.zip

cd php7-ffmpeg-master

rm -f /root/php7-ffmpeg-master/ffmpeg_movie.c

wget --no-check-certificate https://raw.githubusercontent.com/Jan-E/php7-ffmpeg/6fc250beb3d238439d4ef688c3a982811837f94f/ffmpeg_movie.c -O /root/php7-ffmpeg-master/ffmpeg_movie.c

/opt/cpanel/ea-php73/root/usr/bin/phpize

./configure --with-php-config=/opt/cpanel/ea-php73/root/usr/bin/php-config

mv /usr/local/include/libavutil/time.h /usr/local/include/libavutil/time.h_

make

mv /usr/local/include/libavutil/time.h_ /usr/local/include/libavutil/time.h

make install

echo 'extension=ffmpeg.so' > /opt/cpanel/ea-php73/root/etc/php.d/ffmpeg.ini

/bin/systemctl restart httpd.service

**Comment by Jan-E** [comment]
Could you try the Windows Fix branch now? Remove the headers that are still there and try it with your own FFmpeg version.
https://github.com/Jan-E/php7-ffmpeg/tree/windows_fix

**Comment by Jan-E** [comment]
Or try the main branch
