### ISSUE TITLE
ffmpeg shared library not found in Ubuntu 14.04

### ISSUE THREAD

**Issue by emiglobetrotting** [Jan-E/php7-ffmpeg#2]
PHP7 is installed from source due to pthreads. On the same source I wish to install php7-ffmpeg.

In order to do so, I installed php7-ffmpeg in "ext" folder of php-src and then change directory to php7-ffmpeg to run Configure script with

```
./configure && make
```

When run I had ffmpeg header not found error but did the following to solve the ffmpeg header not found error

```
sudo cp php-src/ext/php7-ffmpeg/libavcodec/* /usr/local/include/ffmpeg
sudo cp php-src/ext/php7-ffmpeg/libavdevice/* /usr/local/include/ffmpeg
sudo cp php-src/ext/php7-ffmpeg/libavformat/* /usr/local/include/ffmpeg
sudo cp php-src/ext/php7-ffmpeg/libavutil/* /usr/local/include/ffmpeg
sudo cp php-src/ext/php7-ffmpeg/libswscale/* /usr/local/include/ffmpeg
```

Now I am having the following error

```
checking for ffmpeg libavcodec.so... 
ffmpeg shared libraries not found. Make sure ffmpeg is compiled as shared libraries
using --enable-shared option
```

Though I can find the ffmpeg libraries under /usr/lib/i386-linux-gnu folder.

I've also done this below:

```
echo "/usr/local/lib" >> /etc/ld.so.conf
echo "/usr/lib" >> /etc/ld.so.conf
ldconfig
```

to solve the ffmpeg shared libraries not found error but yet I can't install php7-ffmpeg.

Please I need help on how to install php7-ffmpeg.

**Comment by AlexandrUkr** [comment]
ubuntu 16.04 php 7.0.8 ++

**Comment by grigorov** [comment]
ubuntu 16.04 
stream# php -v
PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )

Error in compile ffmpeg_movie :( 
> stream# make
/bin/bash /home/agrigorov/php7-ffmpeg/libtool --mode=compile cc  -I. -I/home/agrigorov/php7-ffmpeg -DPHP_ATOM_INC -I/home/agrigorov/php7-ffmpeg/include -I/home/agrigorov/php7-ffmpeg/main -I/home/agrigorov/php7-ffmpeg -I /opt/include -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/opt/include/libavcodec/ -I/opt/include/libavformat/ -I/opt/include/libavutil/ -I/opt/include/libswscale/ -I/opt/include/libavfilter/ -I/opt/include/libavdevice/  -DHAVE_CONFIG_H  -g -O2 -Wall -fno-strict-aliasing   -c /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c -o ffmpeg_movie.lo
libtool: compile:  cc -I. -I/home/agrigorov/php7-ffmpeg -DPHP_ATOM_INC -I/home/agrigorov/php7-ffmpeg/include -I/home/agrigorov/php7-ffmpeg/main -I/home/agrigorov/php7-ffmpeg -I /opt/include -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/opt/include/libavcodec/ -I/opt/include/libavformat/ -I/opt/include/libavutil/ -I/opt/include/libswscale/ -I/opt/include/libavfilter/ -I/opt/include/libavdevice/ -DHAVE_CONFIG_H -g -O2 -Wall -fno-strict-aliasing -c /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c  -fPIC -DPIC -o .libs/ffmpeg_movie.o
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:84:31: error: ‘MAX_STREAMS’ undeclared here (not in a function)
     AVCodecContext *codec_ctx[MAX_STREAMS];
                               ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_stream_index’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:172:17: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
                 GET_CODEC_FIELD(fmt_ctx->streams[i]->codec, codec_type) == type) {
                 ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:38:0:
/opt/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_open_movie_file’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:287:9: warning: implicit declaration of function ‘av_close_input_file’ [-Wimplicit-function-declaration]
         av_close_input_file(ffmovie_ctx->fmt_ctx);
         ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:292:9: warning: implicit declaration of function ‘av_open_input_file’ [-Wimplicit-function-declaration]
     if (av_open_input_file(&ffmovie_ctx->fmt_ctx, filename, NULL, 0, NULL) < 0) {
         ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:297:5: warning: implicit declaration of function ‘av_find_stream_info’ [-Wimplicit-function-declaration]
     av_find_stream_info(ffmovie_ctx->fmt_ctx);
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie___construct’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:314:21: warning: unused variable ‘error’ [-Wunused-variable]
  char *key = NULL, *error = NULL;
                     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:314:8: warning: unused variable ‘key’ [-Wunused-variable]
  char *key = NULL, *error = NULL;
        ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:312:47: warning: unused variable ‘hashkey’ [-Wunused-variable]
     char *filename = NULL, *fullpath = NULL, *hashkey = NULL;
                                               ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:311:25: warning: unused variable ‘hashkey_length’ [-Wunused-variable]
     int persistent = 0, hashkey_length = 0;
                         ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:311:9: warning: variable ‘persistent’ set but not used [-Wunused-but-set-variable]
     int persistent = 0, hashkey_length = 0;
         ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_decoder_context’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:541:9: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
         decoder = avcodec_find_decoder(GET_CODEC_FIELD(
         ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:38:0:
/opt/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:552:13: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
             GET_CODEC_PTR(ffmovie_ctx->fmt_ctx->streams[stream_index]->codec);
             ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:38:0:
/opt/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:555:13: warning: implicit declaration of function ‘avcodec_open’ [-Wimplicit-function-declaration]
         if (avcodec_open(ffmovie_ctx->codec_ctx[stream_index], decoder) < 0) {
             ^
In file included from /usr/include/php/20151012/Zend/zend.h:31:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:32:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getComment’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:573:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘comment’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->comment,
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:573:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->comment,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:574:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘comment’
             strlen(ffmovie_ctx->fmt_ctx->comment));
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:573:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->comment,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getTitle’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:588:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘title’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->title,
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:588:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->title,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:589:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘title’
             strlen(ffmovie_ctx->fmt_ctx->title));
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:588:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->title,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getAuthor’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:603:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘author’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->author,
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:603:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->author,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:604:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘author’
             strlen(ffmovie_ctx->fmt_ctx->author));
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:603:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->author,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getCopyright’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:617:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘copyright’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->copyright,
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:617:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->copyright,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:618:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘copyright’
             strlen(ffmovie_ctx->fmt_ctx->copyright));
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:617:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->copyright,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getAlbum’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:632:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘album’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->album,
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:632:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->album,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:633:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘album’
             strlen(ffmovie_ctx->fmt_ctx->album));
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:632:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->album,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getGenre’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:646:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘genre’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->genre,
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:646:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->genre,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:647:40: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘genre’
             strlen(ffmovie_ctx->fmt_ctx->genre));
                                        ^
/usr/include/php/20151012/Zend/zend_types.h:639:23: note: in definition of macro ‘ZVAL_NEW_STR’
   zend_string *__s = (s);     \
                       ^
/usr/include/php/20151012/Zend/zend_API.h:620:33: note: in expansion of macro ‘ZVAL_STRINGL’
 #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
                                 ^
/usr/include/php/20151012/Zend/zend_API.h:638:35: note: in expansion of macro ‘RETVAL_STRINGL’
 #define RETURN_STRINGL(s, l)    { RETVAL_STRINGL(s, l); return; }
                                   ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:646:5: note: in expansion of macro ‘RETURN_STRINGL’
     RETURN_STRINGL(ffmovie_ctx->fmt_ctx->genre,
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getTrackNumber’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:661:37: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘track’
     RETURN_LONG(ffmovie_ctx->fmt_ctx->track);
                                     ^
/usr/include/php/20151012/Zend/zend_types.h:610:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/usr/include/php/20151012/Zend/zend_API.h:631:31: note: in expansion of macro ‘RETVAL_LONG’
 #define RETURN_LONG(l)      { RETVAL_LONG(l); return; }
                               ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:661:5: note: in expansion of macro ‘RETURN_LONG’
     RETURN_LONG(ffmovie_ctx->fmt_ctx->track);
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getYear’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:674:37: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘year’
     RETURN_LONG(ffmovie_ctx->fmt_ctx->year);
                                     ^
/usr/include/php/20151012/Zend/zend_types.h:610:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/usr/include/php/20151012/Zend/zend_API.h:631:31: note: in expansion of macro ‘RETVAL_LONG’
 #define RETURN_LONG(l)      { RETVAL_LONG(l); return; }
                               ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:674:5: note: in expansion of macro ‘RETURN_LONG’
     RETURN_LONG(ffmovie_ctx->fmt_ctx->year);
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_framerate’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:720:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     if (GET_CODEC_FIELD(st->codec, codec_type) == CODEC_TYPE_VIDEO){
     ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:38:0:
/opt/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:724:13: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
             rate = 1 / av_q2d(GET_CODEC_FIELD(st->codec, time_base));
             ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:38:0:
/opt/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_framewidth’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:800:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     return GET_CODEC_FIELD(st->codec, width);
     ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:38:0:
/opt/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_frameheight’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:828:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     return GET_CODEC_FIELD(st->codec, height);
     ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:38:0:
/opt/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getPixelFormat’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:910:11: warning: implicit declaration of function ‘avcodec_get_pix_fmt_name’ [-Wimplicit-function-declaration]
     fmt = avcodec_get_pix_fmt_name(pix_fmt);
           ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:910:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     fmt = avcodec_get_pix_fmt_name(pix_fmt);
         ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_codec_name’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:992:38: error: ‘CODEC_ID_MP3’ undeclared (first use in this function)
         if (decoder_ctx->codec_id == CODEC_ID_MP3) {
                                      ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:992:38: note: each undeclared identifier is reported only once for each function it appears in
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:993:28: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘sub_id’
             if (decoder_ctx->sub_id == 2)
                            ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:995:33: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘sub_id’
             else if (decoder_ctx->sub_id == 1)
                                 ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:998:41: error: ‘CODEC_ID_MPEG2TS’ undeclared (first use in this function)
     } else if (decoder_ctx->codec_id == CODEC_ID_MPEG2TS) {
                                         ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1001:5: warning: ‘codec_name’ is deprecated [-Wdeprecated-declarations]
     } else if (decoder_ctx->codec_name[0] != '\0') {
     ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:37:0:
/opt/include/libavcodec/avcodec.h:1702:22: note: declared here
     char             codec_name[32];
                      ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1002:9: warning: ‘codec_name’ is deprecated [-Wdeprecated-declarations]
         codec_name = decoder_ctx->codec_name;
         ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:37:0:
/opt/include/libavcodec/avcodec.h:1702:22: note: declared here
     char             codec_name[32];
                      ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_read_av_frame’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1251:13: warning: implicit declaration of function ‘avcodec_alloc_frame’ [-Wimplicit-function-declaration]
     frame = avcodec_alloc_frame();
             ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1251:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     frame = avcodec_alloc_frame();
           ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1257:13: warning: implicit declaration of function ‘avcodec_decode_video’ [-Wimplicit-function-declaration]
             avcodec_decode_video(decoder_ctx, frame, &got_frame,
             ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1263:17: warning: ‘av_free_packet’ is deprecated [-Wdeprecated-declarations]
                 av_free_packet(&packet);
                 ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:37:0:
/opt/include/libavcodec/avcodec.h:4492:6: note: declared here
 void av_free_packet(AVPacket *pkt);
      ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1269:9: warning: ‘av_free_packet’ is deprecated [-Wdeprecated-declarations]
         av_free_packet(&packet);
         ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:37:0:
/opt/include/libavcodec/avcodec.h:4492:6: note: declared here
 void av_free_packet(AVPacket *pkt);
      ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_av_frame’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1324:24: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘hurry_up’
             decoder_ctx->hurry_up = 1;
                        ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1326:24: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘hurry_up’
             decoder_ctx->hurry_up = 0;
                        ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_ff_frame’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1381:28: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         ff_frame->av_frame = avcodec_alloc_frame();
                            ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1382:9: warning: ‘avpicture_alloc’ is deprecated [-Wdeprecated-declarations]
         avpicture_alloc((AVPicture*)ff_frame->av_frame, ff_frame->pixel_format,
         ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:37:0:
/opt/include/libavcodec/avcodec.h:5460:5: note: declared here
 int avpicture_alloc(AVPicture *picture, enum AVPixelFormat pix_fmt, int width, int height);
     ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:1388:9: warning: ‘av_picture_copy’ is deprecated [-Wdeprecated-declarations]
         av_picture_copy((AVPicture*)ff_frame->av_frame,
         ^
In file included from /home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:37:0:
/opt/include/libavcodec/avcodec.h:5493:6: note: declared here
 void av_picture_copy(AVPicture *dst, const AVPicture *src,
      ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: At top level:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:143:26: warning: ‘_php_get_ffmovie_ctx’ defined but not used [-Wunused-function]
 static ff_movie_context* _php_get_ffmovie_ctx()
                          ^
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_decoder_context’:
/home/agrigorov/php7-ffmpeg/ffmpeg_movie.c:561:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:196: recipe for target 'ffmpeg_movie.lo' failed
make: *** [ffmpeg_movie.lo] Error 1

**Comment by Jan-E** [comment]
This extension needs FFmpeg 0.7.16, a really old FFmpeg version

**Comment by grigorov** [comment]
thx. all work with 0.7.16
