### ISSUE TITLE
undefined symbol: avcodec_init

### ISSUE THREAD

**Issue by yuxianhua** [Jan-E/php7-ffmpeg#3]
php version:7.1.0
php: symbol lookup error: /usr/local/php/lib/php/extensions/no-debug-non-zts-20160303/ffmpeg.so: undefined symbol: avcodec_init

**Comment by Jan-E** [comment]
This extension needs FFmpeg 0.7.16, a really old FFmpeg version.

**Comment by yuxianhua** [comment]
code:
$ffmpeg = new ffmpeg_movie('old.mp4');
$frame = $ffmpeg->getFrame(10);
$gdImage = $frame->toGDImage();
imagejpeg($gdImage, '10.jpg');
imagedestroy($gdImage);

result:
502 Bad Gateway

**Comment by yuxianhua** [comment]
./configure --with-php-config=/usr/local/php/bin/php-config --with-ffmpeg --enable-skip-gd-check
make && make install

**Comment by Jan-E** [comment]
502 Bad Gateway: are you trying to use the extension on a network stream? Try it on a local file.

**Comment by yuxianhua** [comment]
I was using a local file

code:
$ffmpeg = new ffmpeg_movie('old.mp4');
$frame = $ffmpeg->getFrame(10);
$gdImage = $frame->toGDImage();
imagejpeg($gdImage, '10.jpg');
imagedestroy($gdImage);

**Comment by yuxianhua** [comment]
![image](https://cloud.githubusercontent.com/assets/5378395/22322683/c5654bda-e3d8-11e6-8734-ec08f6bcc1e0.png)

php-fpm error log

**Comment by UnitedMarsupials-zz** [comment]
Try the patches in #3...

**Comment by Jan-E** [comment]
Or try the centos_fix branch, which was created with parts of @UnitedMarsupials 's patches. This fixed the segfault on my CentOS release 6.8 (Final).

See https://github.com/Jan-E/php7-ffmpeg/pull/5#issuecomment-280908139

**Comment by Jan-E** [comment]
Closing in favour of https://github.com/Jan-E/php7-ffmpeg/issues/4
