### ISSUE TITLE
Better care needed with GD-headers

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [Jan-E/php7-ffmpeg#6]
Currently there are `gd.h` and `gd_io.h` bundled with php7-ffmpeg, which is dangerous. On any particular system with php's gd-extension, the actual gd-code could come from two places:

1. A (modified) copy bundled with php itself -- usually some releases behind.
2. A stand-alone build of gd -- usually a newer version than what's bundled with php.

Depending on how php's `configure` was invoked, php may be using its own `libgd/` or the system-provided version. Whichever it is, php7-ffmpeg must use _the same one_. By bundling your own copy of gd's headers, you make conflicts very likely -- php7-ffmpeg's own configure need to figure out, which gd is being used by the php at build-time and arrange for include-path to contain the directory with the right headers.

I'm not sure, what's needed for those headers to be installed -- maybe, one needs to install `gd-devel` or some such -- but bundling them with your own code is dangerous and prone to subtle errors because, for example the `gdImage`-structure may end up different at runtime.

**Comment by Jan-E** [comment]
Good point. I just followed the example of https://github.com/tony2001/ffmpeg-php which was originally used for this repo. ext/gd installs the headers of libgd:
https://github.com/php/php-src/blob/master/ext/gd/config.w32#L82
https://github.com/php/php-src/blob/master/ext/gd/config.m4#L369

So there is a chance that \#include <gd.h> and \#include <gd-io.h> works out-of-the-box. I will check that and commit a fix.

**Comment by Jan-E** [comment]
The VC14 build always uses the bundled libgd now (in the centos_fix branch)
And the *nix ./configure does not have --enable-skip-gd-check anymore, but you have to specify where gd.h and gd-io.gh are located. Typical configure statement:

`
./configure --with-libgd-incdir=/usr/local/php71/include/php/ext/gd/libgd`

**Comment by Jan-E** [comment]
Fixed
