### ISSUE TITLE
PHP Extension on CentOS 7

### ISSUE THREAD

**Issue by Nirjonadda** [Jan-E/php7-ffmpeg#7]
Please can you let me know that How To Install FFmpeg and FFmpeg-PHP Extension on CentOS 7 with cPanel?

**Comment by Jan-E** [comment]
I have no experience with cPanel, so I have no idea.

**Comment by WganMe** [comment]
first use this script order free tested work perfect just php56



https://admin-ahead.com/product/script-solutions-a-ast-ffmpeg-installer/


https://admin-ahead.com/portal/clientarea.php

enter your License Key use option ADVANCED 

https://admin-ahead.com/portal/knowledgebase/43/How-to-install-A-AST-Unified-FFMPEG-Installer-v204.html

after finish install FFMPEG
then do it manual FFMPEG-php not install via script

https://admin-ahead.com/forum/cpanel/ffmpeg-php-module-installation-cpanel-easyapache4/
