### ISSUE TITLE
i have a error on make!!

### ISSUE THREAD

**Issue by go-english** [Jan-E/php7-ffmpeg#8]
/bin/sh /root/php7-ffmpeg/libtool --mode=compile cc  -I. -I/root/php7-ffmpeg -DPHP_ATOM_INC -I/root/php7-ffmpeg/include -I/root/php7-ffmpeg/main -I/root/php7-ffmpeg -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -I/usr/include/libavcodec/ -I/usr/include/libavformat/ -I/usr/include/libavutil/ -I/usr/include/libswscale/ -I/usr/include/libavfilter/ -I/usr/include/libavdevice/  -DHAVE_CONFIG_H  -g -O2 -Wall -fno-strict-aliasing   -c /root/php7-ffmpeg/ffmpeg_movie.c -o ffmpeg_movie.lo 
 cc -I. -I/root/php7-ffmpeg -DPHP_ATOM_INC -I/root/php7-ffmpeg/include -I/root/php7-ffmpeg/main -I/root/php7-ffmpeg -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -I/usr/include/libavcodec/ -I/usr/include/libavformat/ -I/usr/include/libavutil/ -I/usr/include/libswscale/ -I/usr/include/libavfilter/ -I/usr/include/libavdevice/ -DHAVE_CONFIG_H -g -O2 -Wall -fno-strict-aliasing -c /root/php7-ffmpeg/ffmpeg_movie.c  -fPIC -DPIC -o .libs/ffmpeg_movie.o
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_open_movie_file’:
/root/php7-ffmpeg/ffmpeg_movie.c:266: warning: implicit declaration of function ‘avformat_close_input’
/root/php7-ffmpeg/ffmpeg_movie.c:271: warning: implicit declaration of function ‘avformat_open_input’
/root/php7-ffmpeg/ffmpeg_movie.c:276: warning: implicit declaration of function ‘avformat_find_stream_info’
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie___construct’:
/root/php7-ffmpeg/ffmpeg_movie.c:293: warning: unused variable ‘error’
/root/php7-ffmpeg/ffmpeg_movie.c:293: warning: unused variable ‘key’
/root/php7-ffmpeg/ffmpeg_movie.c:291: warning: unused variable ‘hashkey’
/root/php7-ffmpeg/ffmpeg_movie.c:290: warning: unused variable ‘hashkey_length’
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_decoder_context’:
/root/php7-ffmpeg/ffmpeg_movie.c:536: warning: implicit declaration of function ‘avcodec_open2’
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘getDictField’:
/root/php7-ffmpeg/ffmpeg_movie.c:558: error: ‘AVDictionaryEntry’ undeclared (first use in this function)
/root/php7-ffmpeg/ffmpeg_movie.c:558: error: (Each undeclared identifier is reported only once
/root/php7-ffmpeg/ffmpeg_movie.c:558: error: for each function it appears in.)
/root/php7-ffmpeg/ffmpeg_movie.c:558: error: ‘m_entry’ undeclared (first use in this function)
/root/php7-ffmpeg/ffmpeg_movie.c:558: warning: implicit declaration of function ‘av_dict_get’
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_pixelformat’:
/root/php7-ffmpeg/ffmpeg_movie.c:819: error: ‘AV_PIX_FMT_NONE’ undeclared (first use in this function)
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getPixelFormat’:
/root/php7-ffmpeg/ffmpeg_movie.c:835: warning: implicit declaration of function ‘av_get_pix_fmt_name’
/root/php7-ffmpeg/ffmpeg_movie.c:835: warning: assignment makes pointer from integer without a cast
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_codec_name’:
/root/php7-ffmpeg/ffmpeg_movie.c:922: error: ‘AV_CODEC_ID_MPEG2TS’ undeclared (first use in this function)
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_read_av_frame’:
/root/php7-ffmpeg/ffmpeg_movie.c:1175: warning: implicit declaration of function ‘av_frame_alloc’
/root/php7-ffmpeg/ffmpeg_movie.c:1175: warning: assignment makes pointer from integer without a cast
/root/php7-ffmpeg/ffmpeg_movie.c: In function ‘_php_get_ff_frame’:
/root/php7-ffmpeg/ffmpeg_movie.c:1296: warning: assignment makes pointer from integer without a cast

**Comment by WganMe** [comment]
[root@server php7-ffmpeg]# make && make install
/bin/sh /usr/local/src/php7-ffmpeg/libtool --mode=compile cc  -I. -I/usr/local/src/php7-ffmpeg -DPHP_ATOM_INC -I/usr/local/src/php7-ffmpeg/include -I/usr/local/src/php7-ffmpeg/main -I/usr/local/src/php7-ffmpeg -I/opt/cpanel/ea-php70/root/usr/include/php -I/opt/cpanel/ea-php70/root/usr/include/php/main -I/opt/cpanel/ea-php70/root/usr/include/php/TSRM -I/opt/cpanel/ea-php70/root/usr/include/php/Zend -I/opt/cpanel/ea-php70/root/usr/include/php/ext -I/opt/cpanel/ea-php70/root/usr/include/php/ext/date/lib -I/usr/local/ffmpeg/build//include/libavcodec/ -I/usr/local/ffmpeg/build//include/libavformat/ -I/usr/local/ffmpeg/build//include/libavutil/ -I/usr/local/ffmpeg/build//include/libswscale/ -I/usr/local/ffmpeg/build//include/libavfilter/ -I/usr/local/ffmpeg/build//include/libavdevice/  -DHAVE_CONFIG_H  -I/usr/local/ffmpeg/build/include -Wall -fno-strict-aliasing   -c /usr/local/src/php7-ffmpeg/ffmpeg-php.c -o ffmpeg-php.lo 
libtool: compile:  cc -I. -I/usr/local/src/php7-ffmpeg -DPHP_ATOM_INC -I/usr/local/src/php7-ffmpeg/include -I/usr/local/src/php7-ffmpeg/main -I/usr/local/src/php7-ffmpeg -I/opt/cpanel/ea-php70/root/usr/include/php -I/opt/cpanel/ea-php70/root/usr/include/php/main -I/opt/cpanel/ea-php70/root/usr/include/php/TSRM -I/opt/cpanel/ea-php70/root/usr/include/php/Zend -I/opt/cpanel/ea-php70/root/usr/include/php/ext -I/opt/cpanel/ea-php70/root/usr/include/php/ext/date/lib -I/usr/local/ffmpeg/build//include/libavcodec/ -I/usr/local/ffmpeg/build//include/libavformat/ -I/usr/local/ffmpeg/build//include/libavutil/ -I/usr/local/ffmpeg/build//include/libswscale/ -I/usr/local/ffmpeg/build//include/libavfilter/ -I/usr/local/ffmpeg/build//include/libavdevice/ -DHAVE_CONFIG_H -I/usr/local/ffmpeg/build/include -Wall -fno-strict-aliasing -c /usr/local/src/php7-ffmpeg/ffmpeg-php.c  -fPIC -DPIC -o .libs/ffmpeg-php.o
In file included from /usr/include/sys/stat.h:106:0,
                 from /opt/cpanel/ea-php70/root/usr/include/php/Zend/zend_stream.h:28,
                 from /opt/cpanel/ea-php70/root/usr/include/php/Zend/zend.h:41,
                 from /opt/cpanel/ea-php70/root/usr/include/php/main/php.h:35,
                 from /usr/local/src/php7-ffmpeg/ffmpeg-php.c:40:
/usr/include/bits/stat.h:91:21: error: field 'st_atim' has incomplete type
     struct timespec st_atim;  /* Time of last access.  */
                     ^
/usr/include/bits/stat.h:92:21: error: field 'st_mtim' has incomplete type
     struct timespec st_mtim;  /* Time of last modification.  */
                     ^
/usr/include/bits/stat.h:93:21: error: field 'st_ctim' has incomplete type
     struct timespec st_ctim;  /* Time of last status change.  */
                     ^
/usr/include/bits/stat.h:152:21: error: field 'st_atim' has incomplete type
     struct timespec st_atim;  /* Time of last access.  */
                     ^
/usr/include/bits/stat.h:153:21: error: field 'st_mtim' has incomplete type
     struct timespec st_mtim;  /* Time of last modification.  */
                     ^
/usr/include/bits/stat.h:154:21: error: field 'st_ctim' has incomplete type
     struct timespec st_ctim;  /* Time of last status change.  */
                     ^
In file included from /opt/cpanel/ea-php70/root/usr/include/php/Zend/zend_stream.h:28:0,
                 from /opt/cpanel/ea-php70/root/usr/include/php/Zend/zend.h:41,
                 from /opt/cpanel/ea-php70/root/usr/include/php/main/php.h:35,
                 from /usr/local/src/php7-ffmpeg/ffmpeg-php.c:40:
/usr/include/sys/stat.h:366:31: error: array type has incomplete element type
         const struct timespec __times[2],
                               ^
/usr/include/sys/stat.h:373:54: error: array type has incomplete element type
 extern int futimens (int __fd, const struct timespec __times[2]) __THROW;
                                                      ^
In file included from /opt/cpanel/ea-php70/root/usr/include/php/main/php.h:394:0,
                 from /usr/local/src/php7-ffmpeg/ffmpeg-php.c:40:
/opt/cpanel/ea-php70/root/usr/include/php/Zend/zend_virtual_cwd.h:218:2: error: unknown type name 'time_t'
  time_t                         expires;
  ^
/opt/cpanel/ea-php70/root/usr/include/php/Zend/zend_virtual_cwd.h:248:86: error: unknown type name 'time_t'
 CWD_API realpath_cache_bucket* realpath_cache_lookup(const char *path, int path_len, time_t t);
                                                                                      ^
make: *** [ffmpeg-php.lo] Error 1
